version: '3.8'

services:
  notification_services:
    build:
      context: .
      dockerfile: NotificationServices/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    ports:
      - "8081:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - microservices-network

  user_services:
    build:
      context: .
      dockerfile: UserServices/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    ports:
      - "8082:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
